# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_evol.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1530, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(1040, 10, 441, 261))
        self.tabWidget.setObjectName("tabWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.scaleEn = QtWidgets.QSpinBox(self.page0)
        self.scaleEn.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.scaleEn.setMinimum(100)
        self.scaleEn.setMaximum(10000)
        self.scaleEn.setSingleStep(100)
        self.scaleEn.setProperty("value", 1000)
        self.scaleEn.setObjectName("scaleEn")
        self.tabWidget.addTab(self.page0, "")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.scaleMin = QtWidgets.QSpinBox(self.page1)
        self.scaleMin.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.scaleMin.setMinimum(100)
        self.scaleMin.setMaximum(10000)
        self.scaleMin.setSingleStep(100)
        self.scaleMin.setProperty("value", 1000)
        self.scaleMin.setObjectName("scaleMin")
        self.tabWidget.addTab(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.comboGen = QtWidgets.QComboBox(self.page2)
        self.comboGen.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.comboGen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboGen.setObjectName("comboGen")
        self.spinMutChance = QtWidgets.QSpinBox(self.page2)
        self.spinMutChance.setGeometry(QtCore.QRect(10, 50, 51, 31))
        self.spinMutChance.setMaximum(100)
        self.spinMutChance.setProperty("value", 25)
        self.spinMutChance.setObjectName("spinMutChance")
        self.spinMutTimes = QtWidgets.QSpinBox(self.page2)
        self.spinMutTimes.setGeometry(QtCore.QRect(70, 50, 51, 31))
        self.spinMutTimes.setMinimum(1)
        self.spinMutTimes.setMaximum(30)
        self.spinMutTimes.setProperty("value", 3)
        self.spinMutTimes.setObjectName("spinMutTimes")
        self.boxDouble = QtWidgets.QCheckBox(self.page2)
        self.boxDouble.setGeometry(QtCore.QRect(10, 90, 111, 21))
        self.boxDouble.setFocusPolicy(QtCore.Qt.NoFocus)
        self.boxDouble.setChecked(True)
        self.boxDouble.setObjectName("boxDouble")
        self.boxMulti = QtWidgets.QCheckBox(self.page2)
        self.boxMulti.setGeometry(QtCore.QRect(10, 120, 111, 21))
        self.boxMulti.setFocusPolicy(QtCore.Qt.NoFocus)
        self.boxMulti.setChecked(True)
        self.boxMulti.setObjectName("boxMulti")
        self.tabWidget.addTab(self.page2, "")
        self.boxX = QtWidgets.QSpinBox(self.centralwidget)
        self.boxX.setGeometry(QtCore.QRect(1040, 280, 51, 31))
        self.boxX.setFocusPolicy(QtCore.Qt.NoFocus)
        self.boxX.setProperty("value", 49)
        self.boxX.setObjectName("boxX")
        self.boxY = QtWidgets.QSpinBox(self.centralwidget)
        self.boxY.setGeometry(QtCore.QRect(1100, 280, 51, 31))
        self.boxY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.boxY.setProperty("value", 14)
        self.boxY.setObjectName("boxY")
        self.btnUpdateCell = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdateCell.setGeometry(QtCore.QRect(1160, 280, 81, 31))
        self.btnUpdateCell.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUpdateCell.setObjectName("btnUpdateCell")
        self.listGenom = QtWidgets.QListWidget(self.centralwidget)
        self.listGenom.setGeometry(QtCore.QRect(1040, 320, 171, 171))
        self.listGenom.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listGenom.setObjectName("listGenom")
        self.comboGenChange = QtWidgets.QComboBox(self.centralwidget)
        self.comboGenChange.setGeometry(QtCore.QRect(1040, 500, 171, 31))
        self.comboGenChange.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboGenChange.setObjectName("comboGenChange")
        self.changeGen = QtWidgets.QPushButton(self.centralwidget)
        self.changeGen.setGeometry(QtCore.QRect(1040, 540, 171, 31))
        self.changeGen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.changeGen.setObjectName("changeGen")
        self.currInfo = QtWidgets.QLabel(self.centralwidget)
        self.currInfo.setGeometry(QtCore.QRect(1220, 320, 161, 171))
        self.currInfo.setText("")
        self.currInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.currInfo.setObjectName("currInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1530, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Evolution"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page0), _translate("MainWindow", "Enegry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page1), _translate("MainWindow", "Minerals"))
        self.spinMutChance.setToolTip(_translate("MainWindow", "Шанс мутации в %"))
        self.spinMutTimes.setToolTip(_translate("MainWindow", "Количество мутаций"))
        self.boxDouble.setText(_translate("MainWindow", "Разделение"))
        self.boxMulti.setText(_translate("MainWindow", "Увеличение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page2), _translate("MainWindow", "Genoms"))
        self.btnUpdateCell.setText(_translate("MainWindow", "Обновить"))
        self.changeGen.setText(_translate("MainWindow", "Заменить ген"))
